name: Execute algorithm and evaluate metrics

on:
  push:
    branches: [ "main" ]
    paths: 'algorithms/*.yaml'
  pull_request:
    branches: [ "main" ]
    paths: 'algorithms/*.yaml'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Find updated algorithm
        id: find-algorithm
        uses: tj-actions/changed-files@v44
        with:
          files: algorithms/**.yaml

      - name: Execute algorithm container
        run: |
          # iterate over all datasets in S3
          for recording in $(aws s3api list-objects --bucket ${AWS_BUCKET} --prefix datasets --output text --query 'Contents[].[Key]' | grep '.*edf'); do

            # save each recording (dataset slice) to a temp file
            aws s3 cp s3://${AWS_BUCKET}/${recording} /data/tmp.edf

            # Run inference on recording for every updated algorithm
            for algo in ${{ steps.find-algorithm.outputs.all_changed_files }}; do

              IMAGE=$(grep '^image: ' $algo | sed 's/^image: \+//' | tr -d \'\")
              docker run \
                -e INPUT=tmp.edf
                -o OUTPUT=tmp.tsv
                -v /predictions:/output:rw \
                -v /data:/data:ro \
                "${IMAGE}"

              # Upload predictions to S3
              subpath=${recording#*/}
              prediction=${subpath%_eeg.edf}_events.tsv
              aws s3 cp \
                /predictions/tmp.tsv \
                "s3://${AWS_BUCKET}/submissions/${algo_name}/${prediction}"
              rm /data/tmp.edf /predictions/tmp.tsv
            done
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET: ${{secrets.AWS_BUCKET }}

  evaluate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-evaluator:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:

      - name: Evaluate algorithm predictions
        run: python __main__.py
          


  upload:
    runs-on: ubuntu-latest
    steps:
      - name: upload to s3

