name: Update Citations

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-bib-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./citations

      - name: Run citation updater
        run: python citations/update_citations.py

      - name: Commit updated citations.bib
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: Update citations.bib"
          file_pattern: "website/static/bib/citations.bib"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
